# Mathematical statements

## Definition

Quite simply, if a statement is good (clear and non-paradoxical) and has a clearly-defined truth value (even if you don't know what that truth value is), it is described as a **mathematical statement**.

Statements which fail to qualify as mathematical statements are called **non-mathematical statements**.

## Mathematical statements don't need to be about mathematics!

Before we move on, we need to address a really important point. When we say something is a mathematical statement, it does not have to be about mathematics!!

Let's look at some examples of mathematical and non-mathematical statements:

```{example}
Bishkek is the capital of the Kyrgyz Republic.

This is a mathematical statement, even though it's not talking about mathematics! It is mathematical because it is clear, all terms are defined, and it has a clearly-defined truth value (true).

```

```{example}
Malta is the largest country in the world

This is also a mathematical statement, despite not being about mathematics. It is clear, all terms are defined, and it has a clearly-defined truth value (false). 

```

```{example}
$356$ and $989$ have no common divisors.

This is a mathematical statement - it will have a clearly-defined truth value.

```

```{example}
There is a smallest elementary particle, one that can't be divided into smaller particles.

This is a mathematical statement. All terms are easy to Google, and the statement will have a clearly-defined truth value (though it's currently unknown^[See https://www.youtube.com/watch?v=ZorRPAD32i4 for what might be smaller than leptons and quarks, and https://www.youtube.com/watch?v=ehHoOYqAT\_U for a nice introduction to elementary particles.]).

```

```{example}
Pears are the best fruit.

This is not a mathematical statement because it is an opinion.

```

```{example}
$8$ is better than $14$.

This statement is not mathematical because it is an opinion, and because "better" is not defined, and therefore will not have a clearly-defined truth value.

```

```{example}
The Earth is big.

This is also not mathematical because it is vague and therefore will not have a clearly-defined truth value.

```

## Statements containing mathematics aren't necessarily mathematical!

We should also be clear on another point: Just because a statement contains mathematics, that doesn't mean it's mathematical! 

The statement "8 is a better number than 14" might be about numbers, but it's not mathematical because it doesn't have a clearly-defined truth value.

Equally, the statement "$ab = cd$" is definitely mathematical in its content, but it is not classified a mathematical statement because it doesn't contain enough information to decide on its truth value.

<div class="alert alert-warning" role="alert">
<strong>Careful!</strong> 

Mathematical statements don't have to be about mathematics. They just have to be good, clear statements with a clearly-defined (though possibly unknown) truth value. We use the word mathematical here to describe the *nature* of the statement, rather than its *content*.
</div>

<div class="alert alert-info" role="alert">
```{exercise}
For this exercise, you should write:
  
a. A mathematical statement that is *not* about mathematics.
b. A mathematical statement that *is* about mathematics.
c. A non-mathematical statement that *is* about mathematics.
d. A non-mathematical statement that is *not* about mathematics.

``` 

```{exercise}
Do you know the truth values of the two mathematical statements you wrote in the previous question? If not, do you think you could find out?

```  

```{exercise}
Look back at the twenty-six statements in Exercise 3.7. 

a. How many of them are mathematical statements?
b. How many are non-mathematical statements?

```

```{exercise}
Of those statements in Exercise 3.7 which *are* mathematical statements:

a. Which of them do you know are true?
b. Which do you know are false?
c. Which don't you know the truth value of but you think *someone* in the world does?
d. Do you think there are any to which *no one* in the world knows the answer to?

```
</div>

<div class="alert alert-danger" role="alert">
```{exercise}
Do you think there are mathematical statements to which no one can *ever* know the answer? Can you think of any?
  
```  
</div>

<div class="alert alert-info" role="alert">
```{exercise}
Below are four more statements. Repeat Exercises 4.3 and 4.4 for these statements.
  
a. There are infinitely many square numbers.
b. There are infinitely many prime numbers.^[Watch from 12:30 in this video: https://www.youtube.com/watch?v=OihQPf4mJH4.]
c. There are infinitely many perfect numbers.
d. There is no set^[A set is a collection of items.] whose cardinality^[Cardinality tells you the number of items in a set.] is strictly between that of the integers^[Integers are the whole numbers: ...-3, -2, -1, 0, 1, 2, 3...] and the real numbers^[Real number include both whole and non-whole numbers.].    

``` 
</div>

<div class="alert alert-success" role="alert">
<strong> What have we learnt? </strong> 

- We've learnt that the statement "A is the eighth letter of the Latin alphabet" is a mathematical statement, but  "$a^2 + b^2 = c^2$" is not, because it doesn't have a clearly-defined truth value! 
    
- We've learnt to consider the *nature* of the statement, not its subject, when deciding if it is "mathematical" or not.

</div>