# Axioms and definitions

Now that we fully understand what makes a statement "mathematical", we should discuss **axioms** and **definitions**. 

## Axioms are a special kind of mathematical statement

Axioms are mathematical statements which are true, and are *self-evidently* so and therefore cannot be proved. They should be things so obviously true or so universally accepted, that when you read them, you say to yourself, "*Duh, of course!*"^[https://www.merriam-webster.com/dictionary/duh]. Axioms should be so obvious, that when asked to prove them, you end up scratching your head and shouting "C'MON, IT JUST *IS* TRUE!!!!".

Axioms are the building blocks of mathematics. There is no complete list of them all, as we can always add more of them to the list. This chapter contains the axioms which we may use in this course. Tell me if you find a statement which you believe is an axiom but which I've forgotten, and I'll add it to the list below.

### Rules of axioms

- Axioms describe a property of a mathematical object or operation.
- Axioms should never cover more than one property.
- The property each axiom describes is not necessarily unique to the mathematical object, for example the *commutativity* property is true for both multiplication, "$ab = ba$", and addition, "$a+b=b+a$". Similarly "There are infinitely many ways to cut a circle into two equal halves" is also true for spheres: "There are infinitely many ways to cut a spheres into two equal halves".
- Axioms are mathematical statements which are true, elementary and universally accepted, but which don't have proofs (because they are so fundamental).
- Axioms should not be derived from other axioms.

### Axioms about algebra

Here are a few axioms about algebra. Note that $a, b, c$ and $d$ can be *any* numbers.^[See https://www.aaamath.com/ac11.htm.]

- If $a = c$ then $c = a$.
- If $a = c$ and $b = c$, then $a = b$.
- If $a = b$ and $b = c$, then $a = c$.
- If $a = b$ and $c = d$, then $a + c = b + d$.
- $a \cdot b = b \cdot a$.
- If $a = b$ and $c = d$, then $ac = bd$.

### Axioms about geometry

Here are a few axioms about geometry.^[See https://en.wikipedia.org/wiki/Foundations_of_geometry, http://web.mit.edu/wwmath/vectorc/3d/old/axioms.html, https://www.ams.org/journals/tran/1904-005-03/S0002-9947-1904-1500678-X/S0002-9947-1904-1500678-X.pdf, and http://www.mrc.uidaho.edu/~rwells/Critical%20Philosophy%20and%20Mind/Chapter%2023.pdf.] Look up any words you don't understand.

- If you have two points, you can draw a straight line which connects them.
- If you have two points, you can always draw a circle with one of the points at the circle's centre and the other on its edge.
- There are infinitely many ways to cut a circle into two equal halves.
- A straight line can be extended in either direction forever.
- Three points can be arranged in such a way that they don't all lie on the same straight line.
- Four points can be arranged in such a way that they don't all lie on the same flat plane.

**Note:** All of these axioms above can be written in even briefer terms, though I haven't done so, in order to ensure clarity. 

<div class="alert alert-info" role="alert">
```{exercise}
Illustrate each of the six geometric axioms above with a pictorial example.

```  
</div>

<div class="alert alert-danger" role="alert">
```{exercise}
Can you think of any more algebraic or geometric statements which you believe are *so* obviously true that they are in fact axioms. Suggest them to me and if they're axioms, I'll add them to this chapter.

It's possible that *you* might consider a statement to be an axiom (something so obviously true that no proof is needed), but someone else might believe it is not self-evident and that a proof is needed. 

That's fine...if challenged to prove something that you believe is an axiom, rise to that challenge!

```  
</div>

## Definitions are a special kind of axiom

Where axioms describe a property of a mathematical object or operation, **definitions** describe mathematical objects or operations themselves. If axioms form the *rulebook* of mathematics, then definitions form the *dictionary* of mathematics.

### Rules of definitions

- Definitions describe a mathematical object or operation.
- Definitions should never cover more than one object or operation.
- Mathematical objects or operations don't have to have just one possible definition (e.g. the meaning of multiplication changes if we're talking about scalars, vectors, matrices, etc.).
- Definitions answer the question, "What is a ...?", for example "What is a square" or "What is an even number?" or "What is multiplication?"
- Definitions can't be proved, they are just accepted by all people doing mathematics.
- Definitions allow us to all agree on key terms in mathematics.
- Definitions can refer to other definitions.

<div class="alert alert-info" role="alert">
```{exercise}
Write definitions for the following objects or operations.

a. A **square number** (or **perfect square**).
b. A **whole number** (or **integer**).
c. A **non-whole number**.
d. **Consecutive** whole numbers.
e. One number **divides** another. (Careful here, I don't simply mean division. Consider that 4 *divides* 12 but that 5 *does not divide* 12.)
f. An **even number**.
g. An **odd number**.
h. The **absolute** (or **modulus**) operation.
i. A **point**.
j. A **line**.

```
</div>

```{solution}
These are *my* definitions, but these are not perfect. Different people might choose different words to describe these things, and your definitions might look different to mine. This isn't a problem as long as our definitions are both clear, and we both mean the same thing!

a. A **square number** (or **perfect square**) is the square of a whole number.
b. **Whole numbers** (or **integers**) are numbers with digits only to the left of the decimal point.
c. **Non-whole numbers** are numbers which have value to the right of the decimal point (and possibly to the left too).
d. Two whole numbers $a$ and $b$ are **consecutive** if either $b = a + 1$ or $a = b + 1$.
e. $a$ **divides** $b$ if $b \div a$ leaves no remainder.
f. **Even numbers** are whole numbers which can be written in the form $2n$, where $n$ is a whole number.
g. **Odd numbers** are whole numbers which *cannot* be written in the form $2n$, where $n$ is a whole number.^[Alternatively: **Odd numbers** are whole numbers which can be written in the form $2n + 1$, where $n$ is a whole number.]
h. The **absolute** (or **modulus**) of a negative number is the positive version of that number.
i. A **point** has no length, width or height.
j. A **line** has length but no width or height.

```

## Exercises

<div class="alert alert-info" role="alert">
```{exercise}
Below are three mathematical statements (i.e. they have clearly-defined truth values). One of them is an axiom, one is a definition and one is just a regular statement. Which is which?
    
a. The sum of the digits of any number divisible by $9$ is itself divisible by $9$.
b. The product of two negative numbers is positive.
c. For two positive numbers $a$ and $b$, $a$ is larger that $b$ if $a - b > 0$.

``` 
</div>

<div class="alert alert-info" role="alert">
```{exercise}
Come up with definitions of the following terms. Try to be concise, but sufficiently clear.

a. A **rectangle**.
b. A **square**.
c. A **straight line**.
d. A **circle**.
e. A **3D shape**.
f. A **rational number**.
g. **Consecutive even numbers**.
h. **Consecutive odd numbers**.
i. **MAX**(   ).
j. **MIN**(   ).
k. An **acute angle**.
l. A **circle's circumference**.
m. A **tangent** to a circle.
n. The **sum** of two numbers.
o. The **difference** of two numbers.
p. The **product** of two numbers.
q. The **ratio** of two numbers.
r. A **cube number** (or **perfect cube**).^[Unlike perfect squares, perfect cubes do not have a small number of possibilities for the last two digits. Except for cubes divisible by $5$, where only $25$, $75$ and $00$ are allowed.]
s. A **triangle**.
t. A **cuboid**.
u. **Adjacent** sides of a triangle.
v. A **multiple** of a number.
w. An **octagon**.
x. Two **perpendicular** lines.
y. A **prime number**.
z. The **proper divisors** (or **proper factors**) of a whole number.

```  

</div>

```{solution}
^[See https://studymaths.co.uk/glossary.php, http://www.mrc.uidaho.edu/~rwells/Critical%20Philosophy%20and%20Mind/Chapter%2023.pdf, https://www.quora.com/Is-there-a-comprehensive-list-of-axioms-and-math-principles-to-make-learning-math-easier, https://sites.math.washington.edu/~aloveles/Math300Summer2011/Math300Axioms.pdf.]

A square number (or perfect square) is the square of a whole number.

Whole numbers (or integers) are numbers with digits only to the left of the decimal point.

Non-whole numbers are numbers which have value to the right of the decimal point (and possibly to the left too).

Two whole numbers a and b are consecutive if either $b = a + 1$ or $a = b + 1$.

$a$ divides $b$ if $b รท a$ leaves no remainder.

Even numbers are whole numbers which can be written in the form $2n$, where $n$ is a whole number.

Odd numbers are whole numbers which cannot be written in the form $2n$, where $n$ is a whole number.

The absolute (or modulus) of a negativenumber is the positive version of that num-ber.

A point has no length, width or height.

A line has length but no width or height.

A rectangle: A 2D shape with four straight sides and four right angles

A straight line:  a line with unchanging slope

A circle:  a shape representing all the points equidistant from a single point

A 3D shape: a shape with width, length and height

A rational number: a number that be expressed at the ratio of two integers

Consecutive even numbers: If a is an even number $2n$, and $b = a+2$, then $a$ and $b$ are consecutive even numbers.

Consecutive odd numbers: If $a$ is an odd number $2n + 1$, and $b = a + 2$, then $a$ and $b$ are consecutive odd numbers.

MAX(  ): Returns the largest of a set of numbers.

MIN(  ):  Returns the smallest of a set of numbers.

An acute angle: An angle measuring between $0$ and $90$ degrees.

A circle's circumference: The distant around the edge of a circle.

A tangent to a circle: A straight line which intercepts a circle only once.

The sum of two numbers: For two numbers $a$ and $b$, their sum is $a + b$.

The difference of two numbers: For two numbers $a$ and $b$, their difference is $a - b$.

The product of two numbers: For two numbers $a$ and $b$, their product is $a \cdot b$.

The ratio of two numbers: For two numbers $a$ and $b$, their ratio is $a / b$.

A cube number (or perfect cube): A perfect cube is the cube of an integer.

A triangle: A three-sided 2D shape.^[According to this song, https://www.youtube.com/watch?v=gHjnGbNBuAw, "three points were two lines meet".]

A cuboid: A 3D shape which has six rectangular faces at right angles to each other.

Adjacent sides of a triangle: Two sides which meet at a common point.

A multiple of a number: The number multiplied by any integer.

An octagon: An eight-sided 2D shape.

Two perpendicular lines: Two straight lines which meet at a right-angle.

A prime number: An integer whose only two unique divisors are $1$ and itself.

The proper divisors (or proper factors) of a whole number: Integers which divide into another integer, excluding the number itself.

```

<div class="alert alert-info" role="alert">
```{exercise}
Use the following questions to check your understanding of some key definitions.

a. Is zero even?
b. Is a square a rectangle?
c. Does $12$ have five or six divisors?
d. How many proper divisors does $25$ have?
e. If a triangle is a "$3$-gon", a pentagon is a "$5$-gon", and an octagon is an "$8$-gon", what is a "$4$-gon"?
f. What's a "$6$-gon"? What's a "$2$-gon"?
g. Is $87$ prime?
h. How many multiples of $7$ are two-digit numbers?
i. How many pairs of adjacent sides does a triangle have?
j. How many of the following are *not* lengths?

  - circumference of a circle
  - perimeter of a rectangle
  - distance between two points
  - width of a cuboid
  - height of a cylinder

```

</div>

<div class="alert alert-success" role="alert">
<strong> What have we learnt? </strong> 

- Axioms are special kinds of mathematical statements; they are ones which are self-evidently true. They are the building blocks of mathematics.
    
- We've also learnt that *really* fundamental axioms are called definitions. They are how we guarantee that you, your fellow mathematicians and your reader all understand what you're talking about!^[See https://en.wikipedia.org/wiki/Vacuous_truth.]

</div>