# Proof by exhaustion

(

Our first method of proof is not perhaps the most interesting, demanding or even the most common. However, it is very quick to unpack and will get us proving things immediately. It will give us a good launch pad onto more involved methods over the next few weeks.

)

Our method this week is called **proof by exhaustion**. This doesn't mean you do it until *you* are exhausted. Rather, you do it until all possibilities are exhausted. It is closely related to another method we will look at in a couple of weeks. Let's relate it to some conjectures:

**Conjecture** | **If true, how to prove by exhaustion?** | **Practical?**
------------- | ------------- | -------------
No Chinese citizen has green eyes | Check eyes of every Chinese citizen | No
All Irish citizens have a vowel in their surname | Check a database of Irish citizens | Possibly
There is no integer $n$ such that $n^2 + n^3 = 100$ | Check possible integers | Yes
The sum of the digits of a multiple of $9$ is itself a multiple of $9$ | Check all multiples of $9$ | No
For any right-angle triangle with hypotenuse $a$ and legs $b$ and $c$, $a^2 = b^2 + c^2$ | Check every possible right-angle triangle | No

Using this method when there are too many cases, as in (1) and (4), will take far too long, unless you've got a quick or systematic way to carry out the check, as in (2). This method works best for conjectures where the number of possibilities is low, as in (3).^[Unless we could prove that there exist only a limited (and small) number of "families" of right-angled triangles. We'll return to this example later, but for now it seems unlikely to be suitable for a proof by exhaustion.]

## Steps

- Identify and list all possibilities.
- Prove that your list definitely contains all possibilities (i.e. you haven't forgotten any).
- Show that the conjecture is true for each of the possibilities on your list.

## Formal definition

To prove "If $P$ then $Q$" by exhaustion, show that
\begin{align}
<center>
If $P_1$ then $Q$.
If $P_2$ then $Q$.
$\vdots$
If $P_n$ then $Q$.
</center>
where $P_1$, $P_2$, ..., $P_n$ are all possible (finitely many) values of $P$.

## Practice

Use these examples to practise. If the conjecture is not in the form **If ... then ...**, make sure you rewrite it before starting the proof. Attempt the proof before checking the solution.

(\#cnj:nigh): If $2 \leq a \leq 7$ and $a \in{\mathbb Z}^+$, then $4 \nmid a^2 + 2$.

```{solution}
https://www.youtube.com/watch?v=ifMZt4l5JIM
(https://www.youtube.com/watch?v=YmbTI91TUp4)

```

(\#cnj:thru): There is a prime number between $8$ and $12$.

```{solution}
https://www.youtube.com/watch?v=eQM778zoB14

```

(

(\#cnj:mike): There is no integer $a$ such that $a^2 + a^3 = 100$.

```{solution}
XXX

```

)

(\#cnj:exit): No square number ends in $8$.

```{solution}
Solution: Watch 0:00-4:20 of https://www.youtube.com/watch?v=k0f7w4xTp1I

```

(\#cnj:send): $97$ is a prime number.

```{solution}
https://www.youtube.com/watch?v=1amtOenZEwU

```

<div class="alert alert-info" role="alert">
```{exercise}
Some of these conjectures are false; disprove them by finding a counterexample. Some of them are true; prove them by exhaustion.

(\#cnj:syndrome): There is no two-digit number which is both a perfect square *and* a perfect cube.

(\#cnj:crush): If $p$ is a prime number and $p > 5$, then $p^4$ ends in 1. (https://www.youtube.com/watch?v=Q_UdUwm3Biw)

(\#cnj:defeat): There is no three-digit number which is a perfect square. 

(\#cnj:rich): $(a + 1)^3\geq 3^a$ for $a\in{\mathbb Z^+}$, $a\leq 4$.

(\#cnj:dive): The product of two non-integers is never an integer.

(\#cnj:stun): No number greater than 2 when written in English, has more letters than the number itself.

(\#cnj:dirty): No number greater than 2 when written in Russian using the Cyrillic alphabet, has more letters than the number itself.

(\#cnj:frighten): There is no perfect square between 4100 and 4200.

(\#cnj:nest): If $p$ is a prime number such that $3 \leq p \leq 23$, then $8 \mid (p+1)(p-1)$.

(\#cnj:cupboard): Every positive integer up to and including 28 is at least one of the following: prime, perfect, triangular, or can be written as $b^c$, where $b\in{\mathbb Z}$ and $c\in{\mathbb Z^+}$, $c > 1$.

``` 

```{exercise}
Some of these conjectures are false; disprove them by finding a counterexample. Some are true; prove them by exhaustion.

(\#cnj:study): Every integer between 20 and 30 (inclusive) can be written as the sum of *exactly* five **non-zero** square numbers.

(\#cnj:curl): If $x$ is a positive integer less than 5, the last digit of $x^5$ is $x$.

(\#cnj:drag): There are fewer square numbers below 50 than prime numbers.

(\#cnj:junior): Every even integer between (and including) 4 and 30 can be written as a sum of two primes.

(\#cnj:world): The sum of two distinct square numbers is a square number. (**Distinct** means the two square numbers can't be the same.)

(\#cnj:landscape): For $x, y, a \in \mathbb R$, if $x > y$ then $ax > ay$.

(\#cnj:write): It's impossible to move a knight from one corner of a chess board to the corner diagonally opposite in 4 moves. (You don't play chess? Look up online how a **knight** moves.)

(\#cnj:wash): Each integer in the set 2, 4, 6, 8, ..., 24, 26 can be written the sum of *at most* three perfect squares.

(\#cnj:cat): There are no integers $a$, $b$ and $c$ such that $(1+\frac{1}{a})(1+\frac{1}{b})(1+\frac{1}{c}) = 2$.

(\#cnj:refund): If the sum of two integers is even, then at least one of the summands is even. (Don't know what a **summand** is? Have a search online...)

``` 

</div>