# Statements

A statement is a remark or declaration. Here are some examples:

- Life is pain.
- I am 19 years old.
- I like your hat.
- London is the capital of Great Britain.

## Non-statements    

So what is *not* a statement? I've listed four types of non-statements below. Can you think of any other types?

### Fragments

- Fish.
- I am.
- Bro.

These are incomplete sentences, and are therefore not statements.
    
### Questions

- What is $2 \cdot 2$?
- Are you going to eat that?
- What is this life if full of care?

Anything that ends with a question mark is not a statement; it's a question.
    
### Implicit answers

- $162.5$
- Yes it is.
- The day after tomorrow.

Anything that answers a question, without explicitly referencing the question, is not a statement. Or at least, not one that we can work with.
    
### Exclamations

- Dang!
- Ura!
- Phew!

## What makes a *good* statement?

Not all statements are equally good! Some are better than others. Follow the rules below for high-quality statements:
    
### All the words should be clear and understandable

All the words in a statement should *either* already be understood by the reader, or should be easy to Google. Let's look at some examples:

<center>

**Bishkek** is the **capital** of the **Kyrgyz Republic**.

</center>

This is nice and clear. We know what the Kyrgyz Republic is, we know what Bishkek is, and we know what a capital is.

<center>

The **human foot** is comprised of 26 **bones**.

</center>

Again, this statement is nice and clear. We know what each term means.
    
<center>

An **atom** of **uranium** has one more **electron** than an **atom** of **protactinium**.

</center>

We might not understand every term here, but we could use Google to find out more.
    
<center>

<span style="color:red">The **candidate** won the **popular vote** but lost the **election**.</span>

</center>

This isn't clear, and no matter how much Googling we do, we won't be able to clarify the details. We need to ask the author of the statement: Which election? Which year? Which candidate?
    
<center>

<span style="color:red">**I love you**.

</center>

On its own, this statement isn't clear enough. Who is speaking, and to whom?

Once we understand that, we need to ask whether **love** is clearly defined? Are we talking about something from the soul? Something biological? Familiar love? Friendship?
    
<center>
        
<span style="color:red">1000 is a **large** number.

</center>

There's only one word here which is not clear: large. It's not clear how the author is defining large. Maybe the author could change the statement to compare it with something:

<center>

1000 is larger than 500.

1000 people died today in our country, the largest **daily total** since the **global pandemic** began.
        
1000 is the largest number for which the **Romans** had a **symbol**.
        
</center>

In all three of these statements, the word ``large'' has now  been given clear meaning.

### No paradoxes!

Paradoxes contradict themselves. These statements rely more on tricks of language:
    
<center>

This statement is not clear.

This statement is false.

The statement below is not true.
The statement above is true. 

</center>
            
Because paradoxes are built to contradict themselves, they aren't much use to us. Therefore we'll avoid them in this course.^[They are good for keeping our brains busy though!]

<div class="alert alert-danger" role="alert">
```{exercise}
Can you find any other paradoxical statements? What makes them paradoxical?
```  
</div>

### Statements should stand on their own

Don't you hate that feeling when you start watching a film but nothing makes sense because you didn't watch the previous films in the series?^[I had watched *none* of the previous Marvel movies before watching *Avengers: Endgame*. I understood nothing and had to spend an hour afterwards quizzing my boyfriend on the Tesseract, the Ancient One, and what Robert Downey Jr. was doing stranded in space. I think I got it.]
    
A good statement should stand on its own, and not rely on the reader knowing previous statements. If it *does* assume knowledge of previous statements, they should be referenced or restated, like including a plot synopsis for the previous movies!

Now it's your turn. Bring your answers to our next class. 

Going forward, all statements will be coloured yellow, \hl{like this!}

```{exercise}
Take a look at the statements below. Are all the terms clear? Do you understand all the terms? If not, do you think you could find out their meaning on your own? Do any of the statements need more explanation by the author?
    
1. It is hot today.
2. It is hotter today than it was yesterday.
3. The highest temperature on record, 54.4$^{\circ}$C or 130$^{\circ}$F, was measured on 16th August 2020 at the Death Valley National Park in California.
4. The explosion in Beirut in August 2020 could have been avoided.
5. 24 is a nice number.
6. 28 is a perfect number.
7. Two negatives make a positive.
8. Aman has a twin sister.
9. Ariana Grande was the most streamed artist of the year.
10. On average it rains more in Wales than it does in Kyrgyzstan.
```

```{solution}
1. It is not clear what hot means. Definitions of hot will vary around the world and from person to person.
2. This is clearer than the previous statement, however we could benefit from knowing where this statement is talking about. Bishkek? New York? Night time? Day time?
3. This is pefectly clear. We know where and when the statement is talking about, that it is referring to a peak temperature, and that it is not claiming that this was indeed the highest temperature ever on Earth, merely that it is the highest on record.

```

```{exercise}
Using the three rules given above, which of the following statements are good? What is wrong with the others?
    
1. The cyrillic alphabet contains 33 letters.
2. Gunnar Garfors has visited every country in the world.
3. People find it harder to concentrate on one task than they used to.
4. Mobile phones have gotten more powerful over time.
5. Video games help people relax.
6. The US is larger than China.
7. The last word of this sentence is.
8. This sentence contains four e's.
9. This sentence contains 3 1's, 1 2 and 2 3's.
10. The longest word in this sentence is "complementary".
```

<div class="alert alert-success" role="alert">
<strong> What have we learnt? </strong> 

- We understand what *isn't* a statement, what's a *bad* statement and what's a *good* statement. 
- We also understand... 

</div>
    
        
In this course, we will only work with good, high-quality statements.
        
Next, let's look at whether good statements are true or not. 

# Truth values

## What is the truth value of a statement?  

Simply, the *truth value* of a statement is whether the statement is true or false. 
    
- The truth value of the statement "Bishkek is the capital of the Kyrgyz Republic" is true. 
- The truth value of the statement "Osh is the capital of the Kyrgyz Republic" is false.

<div class="alert alert-info" role="alert">
```{exercise}
What are the truth values of the following statements?
  
a. $4 + 4 = 9$
b. $3 \cdot 6 = 18$
c. Ice melts above $0^{\circ}$C on Earth.
d. $11,118$ is the largest number in existence.
e. The Earth is closer to the Sun than Jupiter.
f. $a^2+b^2=c^2$, where $a$, $b$, $c = 1$.
g. $a = b+c$.
h. $1000$ is a large number.

```  
</div>

## Clearly defined truth values

Look back up at **Exercise 3.1**. Did you notice how the first 6 statements all have clearly defined truth values: they are either true (b, c and e) or false (a, d and f).
    
What do we mean when we say the statement has a **clearly defined** truth value? 

- **Completeness** - The statement contains enough information for its truth value to be decided. Terms are clearly defined or easily researchable.
- **Objectivity** - The truth value is not based on personal opinion or experience.
- **Mutual exclusivity** - If a statement is true, it can't also be false. If a statement is false, it can't also be true.
- **Universality** - If the statement is true today, it will be true tomorrow, and it was true yesterday.

<div class="alert alert-info" role="alert">
```{exercise}
For this exercise, you should write:

1. A statement which has a **clearly defined** truth value of true.  
2. A statement which has a **clearly defined** truth value of false.
3. A statement which has a **clearly defined** truth value that *only you* know.

```  
</div>
    
## Statements without clearly defined truth values
 
Look again at **Exercise 3.1**. Did you notice how statements g and h *didn't* have clearly defined truth values? Why not?
    
Let's look at g: 

<center>

$a = b + c$

</center>

This statement doesn't contain enough information for us to be able to decide on its truth value. It *can* be true, for example if $a = 5$, $b = 2$ and $c = 3$. But it can also be false, for example if $a$, $b$, $c = 1$. We can't decide, as we know nothing about $a$, $b$, or $c$.
    
Next we'll look at h: 

<center>

$1000$ is a large number.

</center> 

This statement doesn't have a clearly defined truth value because it depends on personal opinion. Younger members of your family might say the truth value of this statement is true, because they are used to using smaller numbers. However an economist or an astrophysicist or a paleontologist (or you) might disagree, because they are used to dealing with numbers much larger than 1000.
    
Let's look at two more examples: 

<center>

$4x>0$

</center> 

Why is the truth value of this statement not clearly defined? It's because there is not enough information. Its truth value depends entirely on the value of $x$, about which we know nothing. If we choose $x$ to be 10, this statement is true, but if we choose $x$ to be $-5$, the statement is false. 

<center>

Bishkek is a big city.

</center> 

We've already said that good statements are clear and specific. The reason for this is so that we can decide their truth value. 
    
In this statement, "big" is a very vague term. The units of measurement aren't clear. Is it referring to area, to the number of people in Bishkek, to the number of buildings, to the size of those buildings? Also, big compared to what? Compared to Karakol? Compared to Osh? Compared to Almaty? Compared to Seoul? Or maybe compared to 100 years ago? Again, it's not clear.

<div class="alert alert-info" role="alert">
```{exercise}
The following statements **do not** have clearly defined truth values. Why not?

a. This math problem is difficult.
b. Damascus is an old city.
c. The largest city in my country is also my capital city.
d. The world is in a bad state right now.
e. $3.14$
f. $x$ is positive.
g. $ab > cd$
h. Tomorrow is Wednesday.
i. $4$ is an unlucky number.

```  

```{exercise}
Write a statement which does not have clearly defined truth value. For what reason(s) does your statement not have a clearly defined truth value?
  
```  
</div>

## Unknown truth values

What if you don't know the truth value of a statement? Does that mean it is not clearly defined?
 
Let's consider the following statement:  

```{example}
$29,999$ is a prime number.^[Go googling if you're not sure what *prime* means!]

```

You probably don't know whether this statement is true or false. I certainly didn't know when I wrote it! However, it's clear that this statement *will* have a clearly defined truth value, even if we don't know what it is:
    
- **Completeness** - The statement contains enough information, and the terms are clear.
- **Objectivity** - The primeness of numbers is not a matter of personal opinion.
- **Mutual exclusivity** - This statement is either true or it is false: 29,999 can't be both prime and not prime. 
- **Universality** - If 29,999 is prime today, it will be prime tomorrow, and it was prime yesterday.

Here's another example:  

```{example}
Earth is the only planet in the entire universe with life.

```
    
- **Completeness** - The statement contains enough information, and the terms are clear (as long as life is clearly defined^[It is possible that people might disagree on what constitutes life, see https://www.theguardian.com/books/2020/aug/06/lyfe-a-new-word-for-aliens-that-takes-a-leaf-out-of-life. However, as long as we agree on a definition of life, this statement will have a clearly defined truth value.]).
- **Objectivity** - The existence (or not) of life on other planets won't be a personal opinion: it either exists or it doesn't.
- **Mutual exclusivity** - This statement is either true or it is false.
- **Universality** - This statement is universal to a point. For example, the truth value of this statement *could* change over time, for example if life appears on a planet sometime in the future. However, considering the huge amounts of time that is required for life to appear, for our purposes this statement has universality.

Despite not knowing the truth value of this statement, it will have a clearly defined truth value. Either Earth *is* the only planet with life (statement's truth value: true) or there are other planets with life somewhere in the universe (statement's truth value: false).
    
However, unlike **Example 3.1**, this statement's truth value is less easy to find out. Googling ``is there life out there?'' isn't going to help, as the answer is not yet known, and might never be known. 

<div class="alert alert-warning" role="alert">
<strong>Careful!</strong> 

Just because we don't know the truth value of a statement, that doesn't mean it doesn't have one!

It's also possible that a statement has a clearly defined truth value that we can or will *never* know.
</div>

<div class="alert alert-info" role="alert">
```{exercise}
Write a statement which does not have clearly defined truth value. For what reason(s) does your statement not have a clearly defined truth value?

``` 

```{exercise}
Which of the following are important for a statement's truth value to be clearly defined?

  - The statement contains enough information.
  - The statement is written in English.
  - The statement is about mathematics.
  - Any terms new to the reader are easy to look up using Google or in a book. 
  - The statement is objectively true or false, not personal opinion.
  - The statement contains numbers.
  - The statement is universally true or false, not just locally.
  - The statement is short.
  - All terms are clear.
  - The statement is not a paradox.
  - Someone else wrote the statement, not me.
  - The statement is typed, not handwritten.
  
```  

```{exercise}
Which of the following statements will have clearly defined truth values? Which *won't* have clearly defined truth values? Why not?

a. No UN member state has a flag which contains purple.
b. SZA is taller than The Weeknd.
c. People find me funnier than you.
d. There is a largest number.
e. $x > 0$.
f. $|x|$ is never negative.
g. All odd numbers end with $1$, $3$, $5$, $7$ or $9$.
h. All even numbers end with $2$, $4$, $6$, $8$ or $0$.
i. $100$ is prime.
j. Poetry is difficult to understand.
k. Earth is the only planet in the universe which contains life.
l. All square numbers are even.
m. There are no solutions to the equation $a^2 + b^2 = c^2$.
n. There are no solutions to the equation $a^3 + b^3 = c^3$.
o. All perfect numbers are even.^[See http://mathforum.org/library/drmath/view/51526.html.]
p. Eating vegetables is good for people's health.
q. All men are created equal.
r. It rained in Bishkek on New Year's Day 2020.
s. All people have black hair.
t. Most people are good.
u. Max is tall.
v. The identity of the oldest person alive is known.
w. $30\mod 7 = 2$.
x. $29\mod 4 = 3$.
y. Japanese is the hardest language for non-native speakers to learn.
z. Japanese is difficult for non-native speakers to learn.

```
</div>

<div class="alert alert-success" role="alert">
<strong> What have we learnt? </strong> 

- We've learnt what it means to be a statement.
- We've learnt what it means to be a *good* statement too. 
- And we've learnt what it means for a good statement to have a *clearly-defined* truth value.

</div>


In our next chapter, we define a new term...

# Mathematical statements

## Definition

Quite simply, if a statement is good (clear and non-paradoxical) and has a clearly-defined truth value (even if you don't know what that truth value is), it is described as a **mathematical statement**.

Statements which fail to qualify as mathematical statements are called **non-mathematical statements**.

## Mathematical statements don't need to be about mathematics!

Before we move on, we need to address a really important point. When we say something is a mathematical statement, it does not have to be about mathematics!!

Let's look at some examples of mathematical and non-mathematical statements:

```{example}
Bishkek is the capital of the Kyrgyz Republic.

This is a mathematical statement, even though it's not talking about mathematics! It is mathematical because it is clear, all terms are defined, and it has a clearly-defined truth value (true).

```

```{example}
Malta is the largest country in the world

This is also a mathematical statement, despite not being about mathematics. It is clear, all terms are defined, and it has a clearly-defined truth value (false). 

```

```{example}
$356$ and $989$ have no common divisors.

This is a mathematical statement - it will have a clearly-defined truth value.

```

```{example}
There is a smallest elementary particle, one that can't be divided into smaller particles.

This is a mathematical statement. All terms are easy to Google, and the statement will have a clearly-defined truth value (though it's currently unknown^[See https://www.youtube.com/watch?v=ZorRPAD32i4 for what might be smaller than leptons and quarks, and https://www.youtube.com/watch?v=ehHoOYqAT\_U for a nice introduction to elementary particles.]).

```

```{example}
Pears are the best fruit.

This is not a mathematical statement because it is an opinion.

```

```{example}
$8$ is better than $14$.

This statement is not mathematical because it is an opinion, and because "better" is not defined, and therefore will not have a clearly-defined truth value.

```

```{example}
The Earth is big.

This is also not mathematical because it is vague and therefore will not have a clearly-defined truth value.

```

## Statements containing mathematics aren't necessarily mathematical!

We should also be clear on another point: Just because a statement contains mathematics, that doesn't mean it's mathematical! 

The statement "8 is a better number than 14" might be about numbers, but it's not mathematical because it doesn't have a clearly-defined truth value.

Equally, the statement "$ab = cd$" is definitely mathematical in its content, but it is not classified a mathematical statement because it doesn't contain enough information to decide on its truth value.

<div class="alert alert-warning" role="alert">
<strong>Careful!</strong> 

Mathematical statements don't have to be about mathematics. They just have to be good, clear statements with a clearly-defined (though possibly unknown) truth value. We use the word mathematical here to describe the *nature* of the statement, rather than its *content*.
</div>

<div class="alert alert-info" role="alert">
```{exercise}
For this exercise, you should write:
  
a. A mathematical statement that is *not* about mathematics.
b. A mathematical statement that *is* about mathematics.
c. A non-mathematical statement that *is* about mathematics.
d. A non-mathematical statement that is *not* about mathematics.

``` 

```{exercise}
Do you know the truth values of the two mathematical statements you wrote in the previous question? If not, do you think you could find out?

```  

```{exercise}
Look back at the twenty-six statements in Exercise 3.7. 

a. How many of them are mathematical statements?
b. How many are non-mathematical statements?

```

```{exercise}
Of those statements in Exercise 3.7 which *are* mathematical statements:

a. Which of them do you know are true?
b. Which do you know are false?
c. Which don't you know the truth value of but you think *someone* in the world does?
d. Do you think there are any to which *no one* in the world knows the answer to?

```
</div>

<div class="alert alert-danger" role="alert">
```{exercise}
Do you think there are mathematical statements to which no one can *ever* know the answer? Can you think of any?
  
```  
</div>

<div class="alert alert-info" role="alert">
```{exercise}
Below are four more statements. Repeat Exercises 4.3 and 4.4 for these statements.
  
a. There are infinitely many square numbers.
b. There are infinitely many prime numbers.^[Watch from 12:30 in this video: https://www.youtube.com/watch?v=OihQPf4mJH4.]
c. There are infinitely many perfect numbers.
d. There is no set^[A set is a collection of items.] whose cardinality^[Cardinality tells you the number of items in a set.] is strictly between that of the integers^[Integers are the whole numbers: ...-3, -2, -1, 0, 1, 2, 3...] and the real numbers^[Real number include both whole and non-whole numbers.].    

``` 
</div>

<div class="alert alert-success" role="alert">
<strong> What have we learnt? </strong> 

- We've learnt that the statement "A is the eighth letter of the Latin alphabet" is a mathematical statement, but  "$a^2 + b^2 = c^2$" is not, because it doesn't have a clearly-defined truth value! 
    
- We've learnt to consider the *nature* of the statement, not its subject, when deciding if it is "mathematical" or not.

</div>

# Axioms

Now that we fully understand what makes a statement mathematical, we should discuss **axioms**. 

## What makes a mathematical statement an axiom?

Axioms are mathematical statements which are true, and are self-evidently so. Basically, they are things so obviously true or so universally accepted, that when you read them, you say to yourself, "*Duh, of course!*"^[https://www.merriam-webster.com/dictionary/duh]. Axioms should be so obvious, that when asked to prove them, you end up scratching your head and shouting "C'MON, IT JUST *IS* TRUE!!!!".

Axioms are the building blocks of mathematics. There is no complete list of them all, as we can always add more of them to the list. On our Miro board, I have created a space called **Our Axioms} where we'll store all the axioms which we may use in this course. Tell me if you find a statement which you believe is an axiom but isn't there.

<div class="alert alert-warning" role="alert">
<strong>Careful!</strong> 

What *you* might consider to be an axiom (something so obviously true that no proof is needed), someone else might believe is not self-evident and that a proof is needed. That's fine...if challenged to prove something that you believe is an axiom, rise to that challenge!
</div>

Rules of axioms:

- These describe a property of a mathematical object or operation.
- The property is not necessarily unique to the mathematical object, for example "$ab = ba$" for multiplication is also true of addition: "$a+b=b+a$", and "There are infinitely many ways to cut a circle into two equal halves" is also true for spheres: "There are infinitely many ways to cut a spheres into two equal halves"
- Axioms are mathematical statements which are TRUE, elementary and universally accepted, but which don't have proofs (because they are so fundamental).
- Axioms should never cover more than one property of an object or operation.
- Axioms should not be able to be derived from other axioms.

Here are a few axioms about **algebra**. Note that $a, b, c$ and $d$ can be *any* numbers.^[See https://www.aaamath.com/ac11.htm.]

- If $a = c$ then $c = a$.
- If $a = c$ and $b = c$, then $a = b$.
- If $a = b$ and $b = c$, then $a = c$.
- If $a = b$ and $c = d$, then $a + c = b + d$.
- $a \cdot b = b \cdot a$.
- If $a = b$ and $c = d$, then $ac = bd$.

Here are a few axioms about **geometry**:^[See https://en.wikipedia.org/wiki/Foundations_of_geometry % http://web.mit.edu/wwmath/vectorc/3d/old/axioms.html % https://www.ams.org/journals/tran/1904-005-03/S0002-9947-1904-1500678-X/S0002-9947-1904-1500678-X.pdf % http://www.mrc.uidaho.edu/~rwells/Critical%20Philosophy%20and%20Mind/Chapter%2023.pdf.]

- If you have two points, you can draw a straight line which connects them.
- If you have two points, you can always draw a circle with one of the points at the circle's centre and the other on its edge.
- There are infinitely many ways to cut a circle into two equal halves.
- A straight line can be extended in either direction forever.
- Three points can be arranged in such a way that they don't all lie on the same straight line.
- Four points can be arranged in such a way that they don't all lie on the same flat plane.

**Note:** All of the axioms above can be written in even briefer terms, though I haven't done so, in order to ensure clarity. 

<div class="alert alert-info" role="alert">
```{exercise}
Illustrate each of the six algebraic axioms above with an example. The first 3 are going to seem *really} obvious!

``` 

```{exercise}
Illustrate each of the six geometric axioms above with an example.

```  

```{exercise}
Before our next class, I want you to think of one algebraic and one geometric statement which you believe are *so* obviously true that they are in fact axioms. Come to Tuesday's class ready to share your proposed axioms. Those which we all agree are axiomatic will be added to **Our Axioms** on Miro. Note that axioms should be nicely short and simple.

```

</div>

## What makes an axiom a definition?

Be careful! Some statements which seem really obvious and fundamental are actually *so* obvious and fundamental that they are **definitions**, not axioms. What's the difference between an axiom and a definition? Well, if you ever bought a Mathematics Dictionary, you would find definitions inside, not axioms.

Rules for definitions:

- These uniquely describe a mathematical object or operation
- Definitions answer the question, "What is a ...?", for example "What is a square" or "What is an even number?" or "What is multiplication?"
- Definitions can't be proved, they are just accepted.
- They allow us to all agree on key terms in mathematics.

Below are some statements which are definitions, not axioms. Each definition's subject is in **bold**.

- A **square number** (or **perfect square**) is the square of a whole number.
 - **Whole numbers** (or **integers**) are numbers with digits only to the left of the decimal point.
- **Non-whole numbers** are numbers which have value to the right of the decimal point (and possibly to the left too).
- Two whole numbers $a$ and $b$ are **consecutive** if either $b = a + 1$ or $a = b + 1$.
- $a$ **divides** $b$ if $b \div a$ leaves no remainder.
- **Even numbers** are whole numbers which can be written in the form $2n$, where $n$ is a whole number.
- **Odd numbers** are whole numbers which *cannot* be written in the form $2n$, where $n$ is a whole number.^[Alternatively: **Odd numbers** are whole numbers which can be written in the form $2n + 1$, where $n$ is a whole number.]
- The **absolute** (or **modulus**) of a negative number is the positive version of that number.
- A **point** has no length, width or height.
- A **line** has length but no width or height.

<div class="alert alert-info" role="alert">
```{exercise}
Below is an axiom, a definition and a (quite obvious) statement. Which is which?
            
Be careful - just because something seems obvious to you, that doesn't mean it's self-evidently true and an axiom of mathematics.
    
a. The sum of the digits of any number divisible by $9$ is itself divisible by $9$.
b. The product of two negative numbers is positive.
c. For two positive numbers $a$, $b$, $a$ is larger that $b$ if $a - b > 0$.

``` 

```{exercise}
Come up with definitions of the following terms. Try to be concise, but sufficiently clear.

a. A **rectangle**.
b. A **square**.
c. A **straight line**.
d. A **circle**.
e. A **3D shape**.
f. A **rational number**.
g. **Consecutive even numbers**.
h. **Consecutive odd numbers**.
i. **MAX**($a, b,  c, d$).
j. **MIN**($a, b,  c, d$).
k. An **acute angle**.
l. A **circle's circumference**.
m. A **tangent** to a circle.
n. The **sum** of two numbers.
o. The **difference** of two numbers.
p. The **product** of two numbers.
q. The **ratio** of two numbers.
r. A **cube number** (or **perfect cube**).^[Unlike perfect squares, perfect cubes do not have a small number of possibilities for the last two digits. Except for cubes divisible by $5$, where only $25$, $75$ and $00$ are allowed.]
s. A **triangle**.
t. A **cuboid**.
u. **Adjacent** sides of a triangle.
v. A **multiple** of a number.
w. An **octagon**.
x. Two **perpendicular** lines.
y. A **prime number**.
z. The **proper divisors** (or **proper factors**) of a whole number.

```  

```{exercise}
Use the following questions to check your understanding of some key definitions.

a. Is zero even?
b. Is a square a rectangle?
c. Does $12$ have five or six divisors?
d. How many proper divisors does $25$ have?
e. If a triangle is a "$3$-gon", a pentagon is a "$5$-gon", and an octagon is an "$8$-gon", what is a "$4$-gon"?
f. What's a "$6$-gon"? What's a "$2$-gon"?
g. Is $87$ prime?
h. How many multiples of $7$ are two-digit numbers?
i. How many pairs of adjacent sides does a triangle have?
j. How many of the following are *not* lengths?

  - circumference of a circle
  - perimeter of a rectangle
  - distance between two points
  - width of a cuboid
  - height of a cylinder

```

</div>

```{solution}
^[See https://studymaths.co.uk/glossary.php, http://www.mrc.uidaho.edu/~rwells/Critical%20Philosophy%20and%20Mind/Chapter%2023.pdf, https://www.quora.com/Is-there-a-comprehensive-list-of-axioms-and-math-principles-to-make-learning-math-easier, https://sites.math.washington.edu/~aloveles/Math300Summer2011/Math300Axioms.pdf.]

A square number (or perfect square) is the square of a whole number.

Whole numbers (or integers) are numbers with digits only to the left of the decimal point.

Non-whole numbers are numbers which have value to the right of the decimal point (and possibly to the left too).

Two whole numbers a and b are consecutive if either $b = a + 1$ or $a = b + 1$.

$a$ divides $b$ if $b รท a$ leaves no remainder.

Even numbers are whole numbers which can be written in the form $2n$, where $n$ is a whole number.

Odd numbers are whole numbers which cannot be written in the form $2n$, where $n$ is a whole number.

The absolute (or modulus) of a negativenumber is the positive version of that num-ber.

A point has no length, width or height.

A line has length but no width or height.

A rectangle: a shape with four straight sides and four right angles

A straight line:  a line with unchanging slope

A circle:  a shape representing all the points equidistant from a single point

A 3D shape: a shape with width, length and height

A rational number: a number that be expressed at the ratio of two integers

Consecutive even numbers: If a is an even number $2n$, and $b = a+2$, then $a$ and $b$ are consecutive even numbers.

Consecutive odd numbers: If $a$ is an odd number $2n + 1$, and $b = a + 2$, then $a$ and $b$ are consecutive odd numbers.

MAX(  ): Returns the largest of a set of numbers.

MIN(  ):  Returns the smallest of a set of numbers.

An acute angle: An angle measuring between $0$ and $90$ degrees.

A circle's circumference: The distant around the edge of a circle.

A tangent to a circle: A straight line which intercepts a circle only once.

The sum of two numbers: For two numbers $a$ and $b$, their sum is $a + b$.

The difference of two numbers: For two numbers $a$ and $b$, their difference is $a - b$.

The product of two numbers: For two numbers $a$ and $b$, their product is $a \cdot b$.

The ratio of two numbers: For two numbers $a$ and $b$, their ratio is $a / b$.

A cube number (or perfect cube): A perfect cube is the cube of an integer.

A triangle: A three-sided 2D shape.

A cuboid: A 3D shape which has six rectangular faces at right angles to each other.

Adjacent sides of a triangle: Two sides which meet at a common point.

A multiple of a number: The number multiplied by any integer.

An octagon: An eight-sided 2D shape.

Two perpendicular lines: Two straight lines which meet at a right-angle.

A prime number: An integer whose only two unique divisors are $1$ and itself.

The proper divisors (or proper factors) of a whole number: Integers which divide into another integer, excluding the number itself.

```

<div class="alert alert-success" role="alert">
<strong> What have we learnt? </strong> 

- Axioms are special kinds of mathematical statements; they are ones which are self-evidently true. They are the building blocks of mathematics.
    
- We've also learnt that *really* fundamental axioms are called definitions. They are how we are sure you, your fellow mathematicians and your reader all understand what you're talking about!^[See https://en.wikipedia.org/wiki/Vacuous_truth.]

</div>