# Proof by cases

# Introduction

This week we have a beautiful method, called \textbf{proof by cases}. Proving something by cases is very similar to proving something by exhaustion. 

# Similarity to proof by exhaustion}

Recall that in a proof by exhaustion, we:

- identify all the possibilities, 
- make sure that we haven’t forgotten any possibilities, and 
- prove $P \rightarrow Q$ for each possibility. 

In proof by cases, we use the same technique. The only difference is the list of possibilities are renamed "\textit{cases}", and each single case is much broader (more general and less specific) than each single possibility in a proof by exhaustion. 

For example, while the list of possibilities in a proof by exhaustion might be each whole number from 1 to 20 or each possible route taken by a knight on a chessboard, the cases in a proof by cases might be \textit{all} negative numbers and \textit{all} non-negative numbers, or \textit{all} even integers between 1 and 20 and \textit{all} odd integers between 1 and 20, or \textit{all} whole numbers and \textit{all} non-whole numbers.

Let's compare a couple of conjectures we previously proved by exhaustion and a couple which can be proved using cases, to see the difference between \textbf{possibilities} in a proof by exhaustion and \textbf{cases} in a proof by cases.

**Conjecture** | **Proof by exhaustion** | **Proof by cases**
------------- | ------------- | -------------

Conjecture \@ref(cnj:send) | The video solution identified four possible divisors of $97$ (using some clever reasoning about prime numbers and the square root of 97 to not identify more possibilities than necessary) and then checked them all. Finding none divided 97, and being satisfied that this list of candidate divisors was complete, the conjecture was declared true. |
Conjecture \@ref(cnj:send) | In the video solution, the list of possibilities was identified as the integers &\\ 
&  0, 1, 2, 3, ..., 9. Again, this list was long &\\
& enough to ensure completeness but not & \\
& longer than it needed to be. & \\
\hline
\textbf{12.1: }\hl{Integers retain} &  & We should first check the \\ 
\hl{their parity when} & & conjecture is true for even  \\
\hl{squared.} & & integers, then check it's \\
& & true for odd integers.\\
& & \textbf{Case 1:} All even integers \\
& & \textbf{Case 2:} All odd integers \\
& & As all integers are either \\
& & even or odd, we're done!\\
\hline
\textbf{12.2: }\hl{For $a, b \in \mathbb R$, } & & As we're dealing with the\\
\hl{$|a + b| \leq |a| + |b|$} & & modulus function*, it \\
& & makes sense to build \\
& & cases by varying the sign \\
& & of $a$ and $b$. We could try: \\
& & \textbf{Case 1:} $a$ and $b$ both $\geq 0$ \\
& & \textbf{Case 2:} $a$ and $b$ both $< 0$ \\
& & \textbf{Case 3:} $a \geq 0$ and $b <0$ \\
& & \textbf{Case 4:} $a < 0$ and $b \geq 0$ \\
& & Notice we can collapse\\
& & cases 3 and 4 into one by \\
& & simply switching the \\
& & letters \textit{without loss of} \\
& & \textit{generality}, so actually \\
& & we only require three cases. \\
\hline
\textbf{12.3: }\hl{\textit{All} perfect squares} & & What do you think?? What\\
\hl{are either a multiple} & & cases should we use??? \\
\hl{of 3 or one more} & &\\
\hl{than a multiple of 3.} & &\\
\hline
\end{tabular}
\end{center}

\vspace{-5mm}

\begin{gather*}
\hspace{-8mm} \text{* Recall that the modulus function states: } |a| = \begin{cases}
  a & \text{for } a \geq 0,\\
  -a & \text{for } a < 0.\\
\end{cases}
\end{gather*}

\newpage

\section {Without loss of generality}
In the table on the previous page, we referred to the phrase "without loss of generality", or simply \textit{w.l.o.g.} We can use it whenever simply switching the letters doesn't fundamentally change the case we're looking at.

\subsection{Example 1}

Consider conjecture \textbf{12.2} from the table,

\begin{center}
    \hl{For $a, b \in \mathbb R$, $|a + b| \leq |a| + |b|$.}
\end{center} 

We use \textbf{Case 1} to check if the conjecture is \textsc{true} when both $a$ and $b$ are non-negative. We use \textbf{Case 2} to check if the conjecture is \textsc{true} when both $a$ and $b$ are negative. Finally, we should check if the conjecture is \textsc{true} if one of $a$ and $b$ is negative and the other is non-negative. We say, \textit{without loss of generality}, that the negative one will be $b$ and the non-negative one will be $a$. 

This means we need just three cases, not four:

\textbf{Case 1:} $a$ and $b$ both $\geq 0$

\textbf{Case 2:} $a$ and $b$ both $< 0$

\textbf{Case 3:} $a \geq 0$ and $b <0$

If we want to demonstrate this conjecture to someone by asking them to pick two numbers, and they pick one negative number and one non-negative number, we can assign the negative one to $b$ and the non-negative one to $a$.\\

\subsection{Example 2}

Consider the conjecture

\begin{center}\textbf{12.4: }\hl{The product of an odd integer and an even integer is even.} 
\end{center}

\vspace{-5mm}

\begin{align*}
    \intertext{We are considering the product of two integers, $a \cdot b$. One of these integers is even, and the other is odd. \\
    W.l.o.g., let's say that $a$ is the even one and $b$ is the odd one, so}
    a &= 2m \\
    b &= 2n + 1 
    \intertext{with $m, n \in \mathbb Z$. Notice I have used two different integers here, $m$ and $n$, as the conjecture doesn't say $a$ and $b$ must be consecutive (though of course they can be).\\
    We have}
    a \cdot b &= (2m)\cdot (2n+1) \\
    &= 4mn + 2m\\ 
    &= 2(2mn+m)
    \intertext{which is clearly even. \hspace{110mm}$\square$}
\end{align*}

\vspace{-10mm}

Again, if I wanted to demonstrate this conjecture to someone by asking them to pick two numbers, one even and one odd, I just assign the even one to $a$ and the odd one to $b$.


If we had made $a$ the odd one and $b$ the even one, the proof would look identical, so our choice of which was odd and which was even was unimportant. That's what w.l.o.g. means!

Sometimes, however, w.l.o.g. doesn't work.  That's because changing the letters \textit{does} fundamentally change the case we're considering. Let's look at an example...

\subsection{Example 3}

Consider the conjecture
    \begin{center}\textbf{12.5: }\hl{The product of two consecutive numbers is even.}\footnote{Note, we could simply use the fact that conjecture \textbf{12.4} is \textsc{true} and our knowledge of the alternating nature of the parity of integers to declare this conjecture \textsc{true}, but I prove it in full here as a useful illustration.}
    \end{center}


We are considering the product of two integers, $a \cdot b$. If two integers $a$ and $b$ are consecutive, then $b = a + 1$. If we multiply them, we get
\begin{align*}
    a \cdot b &= (a)(a+1) \\
    &= a^2 + a
    \intertext{but it isn't obvious that this is even, so we'll need a new strategy.  \\
    As $a$ and $b$ are consecutive integers, one is even, and the other is odd, because parity alternates for integers.\\
    Let's make $a$ the even one and $b$ the odd one, so,}
    a &= 2m \\
    b &= 2m + 1 
    \intertext{Their product is}
    (2m)\cdot (2m+1) &= 4m^2 + 2m\\
    &= 2(2m^2+m) 
    \intertext{which is clearly even. \\
    But notice, this proof only covers pairs of consecutive integers where the smaller number is even, for example 2 and 3, 4 and 5, or $-2$ and $-1$. It does \textit{not} cover pairs of consecutive integers where the smaller number is odd. If you ask a friend to pick two consecutive numbers and they pick 7 and 8, we must assign 7 to $a$ as it's the smaller of the two numbers, but we \textit{can't} assign 7 to $a$ because we said "let's make $a$ the even one". \\
    We can label the case above as \textbf{Case 1}, then provide a second case, where $a$ is odd and $b$ is even:\\
    \textbf{Case 2: }} 
    a &= 2m + 1 \\
    b &= (2m + 1) + 1 = 2m + 2
    \intertext{The product is}
    (2m + 1)\cdot (2m+2) &= 4m^2 + 4m + 2\\
    &= 2(2m^2+2m + 1) 
    \intertext{which is clearly even. \\
    We've shown that this conjecture is \textsc{true} if the smaller of the two consecutive numbers is even, and if the smaller of the two consecutive numbers is odd. These two cases cover all possible pairs of consecutive numbers, and in both cases, we found the statement to be \text{true}, so the conjecture is \textsc{true}. We are done! \hspace{120mm}}
\end{align*}

\vspace{-10mm}

Here's what the proof looks like in full:
\begin{align*}
    \intertext{\textbf{Conjecture: }The product of two consecutive numbers is even. \\
    \textbf{Proof:} We call our two consecutive numbers $a$ and $b$. W.l.o.g., let $a$ be the smaller of the two. \\
    \textbf{Case 1:} $a$ even, $b$ odd.}
    a &= 2m \\
    b &= 2m + 1 
    \intertext{Thus,}
    a \cdot b &= (2m)\cdot (2m+1) \\
    &= 4m^2 + 2m\\
    &= 2(2m^2+m) 
    \intertext{which is clearly even. \\
    \textbf{Case 2:} $a$ odd, $b$ even.} 
    a &= 2m + 1 \\
    b &= (2m + 1) + 1 = 2m + 2
    \intertext{Thus,}
    a \cdot b &= (2m + 1)\cdot (2m+2) \\
    &= 4m^2 + 4m + 2\\
    &= 2(2m^2+2m + 1) 
    \intertext{which is clearly even. \hspace{110mm}$\square$}
\end{align*}

\vspace{-10mm}

# Knowing when to use cases}\label{section:knowcases}

This will come with practice, I promise!

# Choosing the cases}

Once you have recognised that your proof will require cases (see Part~\ref{section:knowcases}), it can sometimes be difficult deciding how to split the proof up.

The most important thing to remember when using cases is to make them \textbf{distinct} (they should not overlap) and \textbf{complete} (they should consider all possible situations). 

For example, if $P$ says \hl{$a$ is an integer} and you split the proof into positive integers and negative integers, then you have forgotten to consider $a = 0$, and your cases are not complete. You will have to amend one of the two cases to include $a = 0$, or add it as its own case. Similarly, if you have the cases $a \geq 0$ and $a \leq 0$, then 0 is contained in both cases, meaning the cases overlap, which also isn't good. You should amend one of the cases so it no longer includes 0.

Here are some examples of how you might split up a proof into cases, depending on what type of number the conjecture concerns:

\begin{multicols}{2}

\hl{$a \in \mathbb Z$}

\textbf{Case 1:} $a$ is even\\
\textbf{Case 2:} $a$ is odd

\textbf{Case 1:}  $a = 3k$\\
\textbf{Case 2:} $a = 3k + 1$\\
\textbf{Case 3:} $a = 3k + 2$ with $k \in \mathbb Z$

\hl{$a \in \mathbb R$}

\textbf{Case 1:} $a$  is rational\\         
\textbf{Case 2:} $a$ is irrational

\textbf{Case 1:} $|a| > 1$\\
\textbf{Case 2:} $|a| \leq 1$

\hl{$a \in \mathbb Z$ or $\mathbb R$}

\textbf{Case 1:} $a$ is positive\\
\textbf{Case 2:} $a$ is negative\\
\textbf{Case 3:} $a$ = 0

\hl{Pairs of numbers $a, b$}

\textbf{Case 1:} both $a, b > 0$\\
\textbf{Case 2:} both $a, b < 0$\\
\textbf{Case 3:} $a > 0$ and $b < 0$ (w.l.o.g.)\\
\textbf{Case 4:} at least one of $a$ and $b$ equals 0

\textbf{Case 1:} $a,b \neq 0$\\
\textbf{Case 2:} at least one of $a$ and $b$ equals 0
\end{multicols}

\begin{extension}
    \textbf{Extension task}\\
    Verify that for the above examples, the cases are \textbf{distinct} and \textbf{complete}.
\end{extension}

\textbf{Note:} You might split the proof into cases differently to a classmate. Don't worry! There's many ways to prove the same thing - just make sure that when splitting up the problem into cases, you don't miss any numbers!

Once you have split the problem into parts, consider each part \textbf{separately} from one another. 

# How many cases?}

For conjectures in this course that require a proof by cases, you will probably need 2, 3, or maybe 4 cases. However, there is no upper limit for how many you can use. Proofs involving between 5 and 10 cases are common. You should always try to use the smallest number of cases possible.

The first proof of the \textit{Four Colour Theorem}\footnote{The Four Colour Theorem states that any map, like a map of the states of the U.S. or countries of the world, can be coloured using only four colours in such a way that regions sharing a common boundary (other than a single point) do not share the same colour. In other words, a cartographer knows that she needs only four colours to colour \textit{any} map.} used 1936 cases. Since then, mathematicians have managed to reduce this number to close to 600, which is still a lot, but less than 1936!

\begin{Exercise}
All of the conjectures below require a \textbf{proof by cases}. You should first identify the cases required (making sure they are distinct and complete), and show that the conjectures are \textsc{true} for each case.
    \begin{enumerate}[label=\textbf{12.\arabic*}:]
    \setcounter{enumi}{0}
    - Prove \hl{conjecture \textbf{12.1}} from the table earlier in this chapter. Remember that we discussed the cases for this conjecture in the table.\\
    - Prove \hl{conjecture \textbf{12.2}} from the table earlier in this chapter. Remember that we discussed the cases for this conjecture in the table and on page 53.\\
    - Prove \hl{conjecture \textbf{12.3}} from the table earlier in this chapter. \textit{You} will have to decide on the cases for this one. Your classmates might make different choices to you, and that's OK!\\
    - \hl{Conjecture \textbf{12.4}} we've ALREADY PROVED (on page 53).\\
    - \hl{Conjecture \textbf{12.5}} we've ALREADY PROVED (on pages 54 and 55).\\
    - \hl{If $a$ and $b$ are integers, $a^2b^2$ is even.}\\
    - \hl{For all numbers $a, b, c$, if $ab = bc$ then $a = c$.}\\
    - \hl{For any integer $a$, $(3a-1)$ is a multiple of 2.}\\
    - \hl{$5a+6$ has the same parity as $a$.}\\
    - \hl{The sum of two consecutive numbers is odd.}\\
    - \hl{Let $a$ be an integer. Then $a^{2} + a$ is even.}\\
    - \hl{There are no negative square numbers.}
\end{enumerate}
\end{Exercise}

\begin{Exercise}
Some of these conjectures are \textsc{false}; disprove them by finding a counterexample. Some of them are \textsc{true}; prove them using \ul{\textbf{EITHER}} a proof by exhaustion, a direct proof or a proof by cases, unless directed otherwise.
    \begin{enumerate}[label=\textbf{12.\arabic*}:]
    \setcounter{enumi}{12}
    - \hl{There is no integer $a$ such that $a^2 + a^3 = 100$.} \\
        - Prove this conjecture using cases \hlgreen{$a \in \mathbb Z^-$}, \hlgreen{$a = 0$}, \hlgreen{$a \in \mathbb Z^+$ with $a < 5$}, and \hlgreen{$a \in \mathbb Z^+$ with $a \geq 5$}. \\
        - Now prove this conjecture again, either using a proof by cases with a different set of cases (your choice which ones) or using a different method of proof. \\
        
    - \hl{If $a$ is prime, then $a + 13$ isn't.} \\
        
    - \hl{There is no two-digit prime number (with different digits) which is still prime when you swap its digits.} \\
        
    - \hl{For every $a \in \mathbb Z^+$, $a^2 - a + 11$ is prime.}\\

    - \hl{Zero is even.} \\
        
    - \hl{For any pair of integers $a$ and $b$, there is an integer $c$ such that $a^2 + b^2 = c^2$, where $c > a$ and $c > b$.} \\

    - \hl{$a^2 + a^3$ is even for all integers $a$.} \\
        
    - \hl{MAX($a, b$) + MIN($a, b) = a + b$ for any $a$ and $b$.} \\
        
    - \hl{If $a>c$ and $b>c$ for any numbers $a,b$ and $c$, then MAX$(a,b) - c$ is always positive.} \\
        %\item If an integer $n$ is not divisible by 3,  then $n^2=3k+1$ where $k$ is a whole number
        
    - \hl{Let $a$ be an integer. If 3 does not divide $a$, then 3 does divides $a^2 - 1$.}
\end{enumerate}
\end{Exercise}

\begin{Exercise}
Some of these conjectures are \textsc{false}; disprove them by finding a counterexample. Some of them are \textsc{true}; prove them using \ul{\textbf{EITHER}} a proof by exhaustion, a direct proof or a proof by cases.
    \begin{enumerate}[label=\textbf{12.\arabic*}:]
    \setcounter{enumi}{12}
    - \hl{If $a$ and $b$ are both positive integers and $n = ab$, then either $a \leq \sqrt{n}$ or $b\leq \sqrt{n}$.} \\
        
    - \hl{The only way for $3a^2 + 4a + 3$ to be even is if $a$ is odd.} \\
        
    - \hl{For integers $a$, $b$, $c$, $d$ and $n$, $(an + b)$ and $(cn + d)$ have different parity to one another only when $a$ and $b$ have different parity to one another AND $c$ and $d$ have different parity to one another.} \\
        
        Today's date is 03/12/2020, which contains lots of repeated digits: three 0's and three 2's. The last three dates with \textit{no} repeated digits were probably before you were born: 23/06/1987, 24/06/1987 and 25/06/1987.
    - \hl{The next date this will happen is over 300 years in the future.}\\
        
        The game \textbf{Tenzi} (https://ilovetenzi.com) uses forty 6-sided dice, each numbered 1 to 6.
    - \hl{If you roll all forty dice at the same time, at least seven will land on the same number.}\\
        
    - \hl{127 is prime.}\\
        
    - \hl{If $a$ is an integer, then $a^2 + 1$ is prime.}\\
        
    - \hl{If $a > 0$, then $\sqrt a < a$.}\\
        
        You have 27 small cubes, 3 each of nine different colours.
    - \hl{You can use all these small cubes to make a 3 x 3 x 3 cube so that \textit{each} face of the bigger cube contains one of each of the nine colours.}
        
\end{enumerate}
\end{Exercise}
