# Proof by contradiction CONJECTURES

<div class="alert alert-info" role="alert">
```{exercise}
Some of these conjectures are false; disprove them by finding a counterexample. Some of them are true; prove them using one (or a combination of more than one) of the methods we've met so far.

```

(\#cnj:zaibatsus): $\sqrt{3}$ is irrational.

(\#cnj:zany): $\pi$ is irrational.

(\#cnj:zamindar): $3a + 5b$ is even only when $a$ and $b$ are both integers.

(\#cnj:zaniness): The product of three consecutive positive integers is never a perfect cube.

(\#cnj:zapateos): The product of three consecutive integers is never a perfect cube (ignoring the trivial case where one of the three numbers is $0$). <br /> *Hint: Build on your work from Conjecture \@ref(cnj:zaniness).*

(\#cnj:zappiest): In a right angled triangle,^[A right triangle is a triangle containing a $90^\text{o}$ angle.] the length of the hypotenuse is always less than the sum of the lengths of the two other sides.

(\#cnj:zaptiahs): Every perfect cube is either a multiple of $9$, one more than a multiple of $9$ or one less than a multiple of $9$.

(\#cnj:zaratite): The sum of two positive numbers is also positive. 
<!-- Prove it by contradiction. We've got our proposition, which means our supposition is the opposite: The sum of two positive numbers is not always positive. Or, in other words: There exist two positive numbers a and b that sum to a negative number. -->
<!-- % Proof time. Putting our supposition in math lingo, we get: a + b < 0 Their sum needs to be negative, or less than 0. Let's rearrange our inequality a bit. How 'bout we subtract b from both sides? a < -b Our supposition implies that a must be less than -b. But since b is a positive number, -b must be a negative number. That would mean that a, which is positive, is less than b, which is negative. Hold the phone: anything less than a negative would also be negative. Uh, a can't be positive and negative at the same time. That would probably destroy the universe in a puff of purple smoke, and we can't have that. -->
<!-- % We've found our contradiction: if a and b are both positive, a can't possibly be less than -b. Let's formalize this mess. "Since a + b < 0 implies that a < -b when both a and b are positive, which means a is also negative, this contradicts the supposition that there exist two positive numbers a and b that sum to a negative number. Hence, our original proposition is true: the sum of two positive numbers is always positive." -->

(\#cnj:zareebas): If $a^2$ is an integer, then so is $a$.

(\#cnj:zarzuela): If $a$ is a perfect square, then $a + 2$ isn't.
<!-- https://math.stackexchange.com/questions/537286/prove-that-if-n-is-a-perfect-square-then-n2-is-not-a-perfect-square -->

(\#cnj:zastruga): If $a$ is a perfect square, then $a^2$ isn't. 

(\#cnj:zastrugi): Every triangle has at least one obtuse angle.

<!-- %(\#cnj:zealotry): Every triangle has at least two acute angles. -->

<!-- (\#cnj:zecchini): There is no integer that is both even and odd. -->

(\#cnj:zecchino): For any pair of integers $a$ and $b$, $(a + b)^2 = a^2 + b^2$.

(\#cnj:zelkovas): For any pair of integers $a$ and $b$, $\sqrt{a + b} = \sqrt{a} + \sqrt{b}$.

(\#cnj:zemindar): $a^2 + a^3$ is even for any integer $a$.

(\#cnj:zenithal): For any integer $a$, $4 \nmid (a^2 - 3)$.

(\#cnj:zeolitic): There's no positive integer $a$ such that $a^2 - 2a$ is negative.

(\#cnj:zeppelin): There's no positive integer $a$ such that $a(a+1)$ is a perfect square.

<!-- (\#cnj:zestiest): No cube has a surface area that's equal to its volume. -->

<!-- (\#cnj:zestless): No non-cube cuboid has a surface area that's equal to its volume. -->

<!-- (\#cnj:zibeline): No circular cone has a surface area that's equal to its volume. -->

<!-- (\#cnj:ziggurat): No square-based pyramid has a surface area that's equal to its volume. -->

<!-- (\#cnj:zigzaggy): No triangular-based pyramid has a surface area that's equal to its volume. -->

<!-- (\#cnj:zikkurat): No cylinder has a surface area that's equal to its volume. -->

<!-- (\#cnj:zillion): No sphere has a surface area that's equal to its volume. -->

(\#cnj:zincking): No circle has a circumference that's equal to its area.

(\#cnj:zingiest): No square has a perimeter that's equal to its area.

(\#cnj:zippered): No rectangle has a perimeter that's equal to its area.

<!-- (\#cnj:zippiest): No equilateral triangle has a perimeter that's equal to its area.  -->

<!-- (\#cnj:zircaloy): No non-equilateral but symmetric triangle has a perimeter that's equal to its area. -->

<!-- (\#cnj:zirconia): No non-equilateral, non-symmetric triangle has a perimeter equal to its area. -->
<!-- %((SUPER SPICY!!)) https://sites.google.com/view/enigmaths/polygons/triangle?fbclid=IwAR0f91hdbFEP13-f4wWiF6PPd6rry6nQOyHZZxYZ0KAqYRvzHQoceYZAN4E -->

<!-- %(\#cnj:zirconic): Place three identical squares next to each other in a line so that they touch. From the topmost left corner of the lefthand square, draw a line to each of the bottommost right corners of the three squares. The sum of the three acute angles formed by these lines and the lower horizontal line is 90$^{\circ}$. %https://www.youtube.com/watch?v=m5evLoL0xwg -->

(\#cnj:zizzling): There are a finite amount of Pythagorean Triples.

<!-- (\#cnj:zodiacal): There are no three consecutive numbers where the sum of the squares of the smaller two equals the square of the largest. -->

<!-- (\#cnj:zombiism): There are only a limited number (in other words, not infinite) examples of the previous conjecture. -->

<!-- (\#cnj:zonation): Same as the previous conjecture, but for cubes. -->

</div>