# Proof by contraposition

\textcolor{red}{\textbf{\textsc{Method 4: Proof using the Contraposition |}}  \textit{To prove P$\Rightarrow$Q, prove T$\Rightarrow$S}}
\vspace{2mm}
\begin{tcolorbox}
    \textbf{What?}
    \\To prove that P $ \Rightarrow $ only Q, prove  that T $ \Rightarrow $ only S.
    \vspace{5mm}\\
    \textbf{Steps for a proof by contraposition:}
    \\\underline{Step 1:} Identify P and Q (and then S and T).
    \\\underline{Step 2:} Build the map of the conjecture.
    \\\underline{Step 3:} Prove T only $ \Rightarrow $ S. If this is true, then P only $ \Rightarrow $ Q, и все!
    \vspace{5mm}
    \\\textbf{Why would you use this method?}
    \\For example, if a direct proof requires lots of cases, proving the contraposition might require no cases (or fewer cases), so it can save you time.
\end{tcolorbox}

## Not yet uploaded

\pagebreak
\color{RawSienna}
\vspace{5mm}\hspace{-29mm}{\fontsize{17}{12}\selectfont \textbf{\textit{Raw Sienna} (try to prove these using the contraposition method)}}
\item Every multiple of 3 can be written as the sum of three consecutive numbers.
\item If $a, b$ are both even, then the sum of $a$ and $b$ is even.
\item If $a^2+b^2$ is odd and $a$ and $b$ both whole, then either $a$ or $b$ is even.
\item If $a, b$ and $c$ are a \href{https://www.mathsisfun.com/pythagorean_triples.html}{\ul{Pythagorean triple}}, then at least one of them must be even.

\color{WildStrawberry}
\vspace{5mm}\hspace{-29mm}{\fontsize{17}{12}\selectfont \textbf{\textit{Wild Strawberry}}}
\\{\color{black}
\vspace{2mm}\hspace{-29mm}{Another collection of conjectures which might be false (and which can hopefully can be} 
\\\hspace{-29mm}{disproved using a nice \hl{counterexample}) or which might be true.} %https://cs.brown.edu/courses/csci0220/static/files/documents/templates/counterexample.pdf
\\\vspace{2mm}\hspace{-29mm}{If you can't find a counterexample, it might be true so try a \hl{direct proof} (of P$\rightarrow$Q).} 
\\\vspace{2mm}\hspace{-29mm}{If that's nasty and you are able to draw a map of the conjecture (and it's not a \textsc{type iii}} 
\\\hspace{-29mm}{map!) try a \hl{proof by contraposition}. If none of these work, wait till next Tuesday for our} 
\\\hspace{-29mm}{next method of proof...}}
\\{\color{WildStrawberry}
\item If the product of two whole numbers is even then at least one of them's even.
\item ($a + b - c$) can't be even unless at least one of $a, b$ or $c$ is even.
\item For a whole number $a$, if $a^2$ is even, then $a$ is even.
\item For a whole number $a$, if $a^2$ is odd, then $a$ is odd. 
\item If $2a$ is even, then $a$ must be whole.
\item Every odd number can be written as the sum of two perfect squares.}

\color{Thistle}
\vspace{5mm}\hspace{-29mm}{\fontsize{17}{12}\selectfont \textbf{\textit{Highland Thistle}}}
\\
\vspace{2mm}\hspace{-29mm}{Note, the symbol $|$ means one number is a \textbf{divisor} of another.} 
\\\hspace{-29mm}{For example, 11 is a divisor of 33 and so we can write $11|33$ and 6 is a divisor of 18 so we} 
\\\hspace{-29mm}{can write $6|18$. Similarly, $4|16$, $5|25$, $5|30$, $7|42$ etc.} 
\\\hspace{-29mm}{Note, we're not actually \textit{doing} the division! We're just stating that if you did the division,} 
\\\hspace{-29mm}{the result would be a whole number.} 
\\\hspace{-29mm}{4 is NOT a divisor of 15 so we write $4\nmid15$. Similarly $3\nmid10$, $5\nmid8$, $5\nmid7$, $2\nmid5$, $7\nmid22$, $10\nmid31$}
\item For whole numbers $a, b$ and $c$, if $a|(bc)$, then $a |$ both $b$ and $c$.
\item For whole numbers $a, b$ and $c$, if $a|(bc)$, then $a|$ either $b$ or $c$ or possibly both.
\item For whole numbers $a, b$ and $c$, if $a \nmid (bc)$, then $a \nmid b$.
\item For whole numbers $a$ and $b$, if $5 \nmid (ab)$, then $5 \nmid a$ and $5 \nmid b$. 
\item If $a$ is an odd number, then $8 | (a^2 - 1)$.
\item For a whole number $a$, if $4|a^2$, then $4|a$.
% Amazing direct and contraposition proofs - https://www.people.vcu.edu/~rhammack/BookOfProof2/Contrapositive.pdf
% http://sites.millersville.edu/bikenaga/math-proof/counterexamples/counterexamples.pdf
% Suggestion to call prove by cotraposition 'indirect proof': http://math.northwestern.edu/~mlerma/courses/cs310-05s/notes/dm-proofs.pdf

\pagebreak
\color{OrangeRed}
\vspace{5mm}\hspace{-29mm}{\fontsize{17}{12}\selectfont \textbf{\textit{Watermelon}}}
\item For any non-zero numbers $a, b$ and $c$, if $ab=c$ then at least one of $a, b$ and $c$ is positive.
\item The sum of two consecutive numbers is odd.
\item A triangle has at most one obtuse angle. 
\\ {\color{black}Note: An \textit{obtuse} angle is an angle between $90^\text{o}$ and $180^\text{o}$.}
\item If $a$ is odd, $a^2 + 1$ is even.
%\item If $a$ is odd, $a^3 + 1$ is even.
\item If $(a + b)$ is a multiple of 4, then $(a - b)$ can't be.
\item If $(a + b)$ is a multiple of 3, then $(a - b)$ can't be.

\color{Aquamarine}
\vspace{5mm}\hspace{-29mm}{\fontsize{17}{12}\selectfont \textbf{\textit{Turquoise Stone}}}
\\{\color{black}
\vspace{2mm}\hspace{-29mm}{Practice our new method of \hl{proof by contradiction} with these:}}
\item The sum of two whole numbers is also whole.
\item There are no whole numbers $a$ and $b$ for which $9a - 6b = 1$.
\item There are no non-zero whole numbers $a$ and $b$ for which $a^2 - b^2 = 1$. % From here: http://zimmer.csufresno.edu/~larryc/proofs/proofs.contradict.html
\item There are no whole numbers $a$ and $b$ for which $a^2 - b^2 = 10$.
\item The product of two consecutive numbers is even. {\color{black}(I know we've done this one before, but try to find a proof by contradiction of it.)}
\item There is no largest number. 
% Suppose that a largest number does exist. Let it be L. If L really is the largest number, then there can be no number larger than L. Consider the number L+1. This number is larger than L, but it was just stated that there cannot be any number larger than L. This is a contradiction. The premise that there existed a largest number cannot be true, because the consequence of this premise is absurd. Therefore, there is no largest number. From https://brilliant.org/wiki/contradiction/

\textbf{Proof by contra-position:} Assume $\neg Q$ and aim for $\neg P$
\\If $Q$ hasn't happened, you know $P$ has not happened, or in other words, $Q$ cannot happen without $P$. If $Q$ cannot happen without $P$, then 
\end{tcolorbox}
For contra-position, these two methods are basically the same: if you are able to prove $\neg P$ from $\neg Q$ (the method of contra-position) then because proof by contradiction requires you to assume $P$ then  then that would also yield a contradiction in the proof by contradiction, since you are assuming $P$.
\\So you might as well do a proof by contradiction if you are going to do a proof by contraposition! 
In fact, this is actually how many proofs by contraposition are found: begin with a proof by contradiction, and then after you are done you realise you never use the assumption of $P$, so the proof is rewritten.