# Other methods

## And proof by smallest counterexample: 

https://math.libretexts.org/Bookshelves/Mathematical_Logic_and_Proof/Book%3A_Book_of_Proof_(Hammack)/10%3A__Mathematical_Induction/10.03%3A_Proof_by_Smallest_Counterexample

## Proofs with no words

## Geometric proofs

What follows are more conjectures, *some* of which will require one of the three methods mentioned in this chapter, other which are false, and others which can be proved using another method from this textbook.

They are not ordered by difficulty, so if you get stuck, you can move onto the next one without worrying that it will be even harder! 

I have grouped some similar theorems together. However, this doesn't mean you will prove (or disprove) them in a similar way, though they may rely on each other.

<div class="alert alert-info" role="alert">

Rationals and irrationals <br /> A rational number is a number that can be expressed as the ratio of two integers. <br /> For example $4$ is rational because $4$ can be written as $\frac{4}{1}$ or $\frac{8}{2}$ or $\frac{100}{25}$ etc. <br /> $-3.5$ is rational because it can be written as $\frac{-7}{2}$ or $\frac{-35}{10}$ etc. <br /> $\frac{1}{9} = 0.1111...$ and so $0.1111...$ is a rational number. <br /> $0.142857142857142857...$ is rational because it is $1$ divided by $7$. <br /> $\pi$ is not rational because it can't be written as a fraction of integers.

(\#cnj:japes): There is no rational number $a$ for which $a^3 + a + 1 = 0$.

(\#cnj:jade): The ratio of two rational numbers is rational.

(\#cnj:joke): The sum of two rational numbers is rational.

(\#cnj:jest): The product of two rational numbers is rational.

(\#cnj:jeep): No two numbers in a Pythagorean triple are the same. 
<!-- IRRATIONAL -->

(\#cnj:XXX): If $n$ is an integer not divisible by 5, then $n^2$ leaves a remainder of 1 or 4 when it is divided by 5.

(\#cnj:XXX): For any number $x$, $x^2 \geq x$.

(\#cnj:XXX): If $a + b = 500$ and both $a$ and $b$ are integers greater than 0, the greatest common divisor (gcd) of $a$ and $b$ is not 7.

(\#cnj:XXX): If $a^3 - 1$ is even, then $a$ is odd (for a whole number $a$). 
(\#cnj:XXX): If $a|bc$, then $a |$ both $b$ and $c$.

(\#cnj:XXX): If $a|bc$, then $a|$ either $b$ or $c$ or possibly both.

(\#cnj:XXX): For any numbers $a$ and $b$, if $a^2 | b^3$ then $a | b$.

(\#cnj:XXX): For any integers $a,b$ and $c$, if $a^2 | b$ and $b^3 | c$ then $a^6 | c$.

(\#cnj:XXX): The sum of two even numbers is always even.

(\#cnj:XXX): If both $m + n$ and $n + p$ are even, where $m, n, p \in \Z$, then $m + p$ is even too.

(\#cnj:XXX): There exists only one number which is both odd \textit{and} even.

(\#cnj:XXX): If a whole number is not divisible by 3, then its square is one more than a multiple of 3

(\#cnj:XXX):  NOT USEFUL If $a^2 > b^2$ then $abs(a) > abs(b)$.

(\#cnj:XXX): (REVERSE LOGIC) If $3x - y = z$ (with integers $x, y, z$) then at least one of $x, y, z$ is even.

(\#cnj:XXX): If $3x - y = z$ (with integers $x, y, z$) then at most one of $x, y, z$ is even.

(\#cnj:XXX): $|a||b| = |ab|$ cases

(\#cnj:XXX): If $6x+9y = 22$, then either $x$ or $y$ or both is not an integer..

(\#cnj:XXX): If $6x+9y=22$, then at most one of $x$ and $y$ is a non-integer.

(\#cnj:XXX): It's not possible to sum two integers and get a non-integer.
<!-- NOT USEFUL  -->

(\#cnj:XXX): $3n^2 + n + 14$ is even for any integer $n$.

(\#cnj:XXX): Every integer greater than 3 is equal to the sum of the squares of two integers. 

(\#cnj:XXX): Every integer greater than 3 is equal to the sum of the squares of two numbers (these numbers don't have to be integers).

(\#cnj:XXX): The sum of the first $n$ odd numbers is $n^2$.

(\#cnj:XXX): Ask a friend to give you five whole numbers. You'll always be able to find three of them which sum to a multiple of 3

(\#cnj:XXX): Same but for 4

(\#cnj:XXX): Ask a friend to give you three numbers. The sum of these numbers will always be a multiple of 3.

(\#cnj:XXX): There are an infinite number of differently-shaped rectangles with an area of 18.

(\#cnj:XXX): If $a, b, c, d$ are numbers with $a < b$ and $c < d$, then $ab < cd$.

(\#cnj:XXX): If xys P.T., then  at least one of xyz is odd. [Disprove by multiplying an existing PT by 4]

(\#cnj:XXX): If xyz PT, with x,y < z, then x and y can't both be odd. [Use work from two proofs ago.]

(\#cnj:XXX): $n^7 - n$ is divisible by 7 for all positive integers $n$

(\#cnj:XXX): $3x + 5y$ (where $x$ and $y$ are integers) is even only when $x$ is	odd	and	$y$ is odd.

(\#cnj:XXX): Every integer greater than 2 is equal to the difference of two perfect squares (c-e)

(\#cnj:XXX): For all positive numbers $n, \frac{1}{n} < n$. (c-e)

(\#cnj:XXX): The only way for both $xy$ and $x + y$ to be even is if both $x$ and $y$ are even.

(\#cnj:XXX): There are as many even numbers as natural numbers (even though there even numbers are a subset of the natural numbers).
<!-- Use Gilbert’s hotel to understand this, everyone has a room. -->

(\#cnj:XXX): When $x > 0 $, $\sqrt{x} < x$. (c-e)
 
<!-- In other words is it constructive? -->

(\#cnj:XXX): For all numbers $x$, $-5 \leq |x + 2| - |x - 3| \leq 5$.

(\#cnj:XXX): If more than $n$ pigeons fly into $n$ pigeon holes, then at least one pigeon hole will contain at least two pigeons. (\textit{The Pigeonhole Principle.})

A 52-card deck contains 4 suites (hearts, diamonds, clubs and spades) which each contain 13 different values (A, 1, 2,..., 10, J, Q, K).

- What's the smallest number of cards you need to draw to guarantee that you have a pair? Prove your answer.
- What's the smallest number of cards you need to draw to guarantee that you have a three-of-a-kind? Prove your answer.
- What's the smallest number of cards you need to draw to guarantee that you have a flush (for example, five diamonds)? Prove your answer.
- What's the smallest number of cards you need to draw to guarantee that you have three cards that are either all the same suit or all different suits? Prove your answer.

(\#cnj:XXX): $x^2 = 4y + 3$ has no integer solutions. 
<!-- MOVE UP -->

The popular TV show \textit{Tame of Gnomes} has had 115 episodes. You've watched 60 so far.
(\#cnj:XXX): At least two episodes that you've watched are exactly four episodes apart.

You're at a party with 19 friends. However, not everyone knows each other. You decide to play a game: who knows the most people (excluding you!).
(\#cnj:XXX): At least two people know \textit{exactly} the same number of people at the party. (You can assume that if person $A$ knows person $B$, then person $B$ knows person $A$.)

You live in The Gyzkyr Republic, which issues 5-sym and 8-sym coins, and 10-sym and 50-sym notes.

- What's the largest amount you cannot pay for using only coins?
- What's the largest amount you cannot pay for?
(\#cnj:XXX): Above a certain price, \textit{any} price can be paid for using an even number of both coins. (Not necessarily the same number of each coin.)
(\#cnj:XXX): To pay for an item which is evenly-priced, you must use an even number of at least one of the coins.
(\#cnj:XXX): To pay for an item priced 72 syms, you must use at least 6 of one of the coins
(\#cnj:XXX): Any piece of furniture with four legs is a table.
(\#cnj:XXX): All tables have four legs.
(\#cnj:XXX): If something has a beak, it’s a bird.
(\#cnj:XXX): If the grass is wet, it has rained.
(\#cnj:XXX): Our class does not like sport.
(\#cnj:XXX): If something doesn't have a beak, it’s not a bird

</div>
