# Without loss of generality

Look back at Conjecture 13.2 in the previous chapter. We used four cases in our proof. Whilst there is something fundamentally different about **Cases 1, 2** and **3** (because positive and negative numbers behave differently within the modulus function), **Case 4** is essentially the same as **Case 3**. We can use **Case 3** whenever we have a nonnegative number and a negative number, which covers everything **Case 4** covers, and so **Case 4** is redundant. If, for example, we had $a=-5$ and $b = 2$ (**Case 4**), we can just swap the letters (so $a=2$ and $b = -5$) and this is covered in **Case 3**.

This is referred to as "without loss of generality", or simply *w.l.o.g.* This is an incredibly useful technique, which will save you a lot of time when using proof by cases. We can use it whenever simply switching the letters doesn't fundamentally change the case we're looking at. It doesn't work if switching the letters fundamentally changes the case.

We'll first look at a couple of examples where w.l.o.g. does work, then an example where it doesn't work.

## When w.l.o.g. does work

Conjecture 13.2 (from Chapter 13): For $a, b \in \mathbb R$, $|a + b| \leq |a| + |b|$. 

We use **Case 1** to check if the conjecture is true when both $a$ and $b$ are non-negative. We use **Case 2** to check if the conjecture is true when both $a$ and $b$ are negative. Finally, we should check if the conjecture is true if one of $a$ and $b$ is negative and the other is non-negative. We say, *without loss of generality*, that the non-negative one will be $a$ and the negative one will be $b$.

This means we need just three cases, not four:

**Case 1:** $a$ and $b$ both $\geq 0$.

**Case 2:** $a$ and $b$ both $< 0$.

**Case 3:** $a \geq 0$ and $b <0$.

If we want to demonstrate this conjecture to someone by asking them to pick two numbers, and they pick one negative number and one non-negative number, we can simply assign the non-negative one to $a$ and the negative one to $b$.

***

(\#cnj:hall): The product of an odd integer and an even integer is even.

We are considering the product of two integers, $a \cdot b$. One of these integers is even, and the other is odd.
  
W.l.o.g., let's say that $a$ is the even one and $b$ is the odd one, so

\begin{align}
  a &= 2m \\
  b &= 2n + 1
\end{align}

with $m, n \in \mathbb Z$. Notice I have used two different integers here, $m$ and $n$, as the conjecture doesn't say $a$ and $b$ must be consecutive (though of course they can be). We could now continue with our proof, having halved the amount of work we need to do!

Again, if I wanted to demonstrate this conjecture to someone by asking them to pick two numbers, one even and one odd, I just assign the even one to $a$ and the odd one to $b$. If we had made $a$ the odd one and $b$ the even one, the proof would look identical, so our choice of which was odd and which was even was unimportant. That's what w.l.o.g. means!

Here's the complete proof:

```{proof}
W.l.o.g., let's say that $a$ is the even one and $b$ is the odd one, so

\begin{align}
  a &= 2m \\
  b &= 2n + 1
\end{align}

with $m, n \in \mathbb Z$. 
  
We have

\begin{align}
  a \cdot b &= (2m)\cdot (2n+1) \\
  &= 4mn + 2m\\
  &= 2(2mn+m)
\end{align}

which is clearly even.

```

## When w.l.o.g. doesn't work

Sometimes w.l.o.g. doesn't work.  That's because changing the letters *does* fundamentally change the case we're considering. Let's look at an example...

(\#cnj:hope): The product of two consecutive numbers is even.^[Note, we could simply use the fact that conjecture \@ref(cnj:hall) is true and our knowledge of the alternating nature of the parity of integers to declare this conjecture true, but I prove it in full here as a useful illustration.]

We are considering the product of two integers, $a \cdot b$. If two integers $a$ and $b$ are consecutive, then $b = a + 1$. If we multiply them, we get
  
\begin{align}
    a \cdot b &= (a)(a+1) \\
    &= a^2 + a
\end{align}
    
but it isn't obvious that this is even, so we'll need a new strategy.

As $a$ and $b$ are consecutive integers, one is even, and the other is odd, because parity alternates for integers.

Let's make $a$ the even one and $b$ the odd one, so,
  
\begin{align}
    a &= 2m \\
    b &= 2m + 1  
\end{align} 

Their product is  

\begin{align}
    (2m)\cdot (2m+1) &= 4m^2 + 2m\\
    &= 2(2m^2+m)  
\end{align} 
which is clearly even.

But notice, this proof only covers pairs of consecutive integers where the smaller number is even, for example $(2, 3)$, $(4, 5)$, ($-2$, $-1$). It does *not* cover pairs of consecutive integers where the smaller number is odd, for example $(1, 2)$, $(-1, 0)$, ($7$, $8$). If you ask a friend to pick two consecutive numbers and they pick 7 and 8, we **must** assign 7 to $a$ as it's the smaller of the two numbers, but we *can't* assign 7 to $a$ because we said "let's make $a$ the even one".

We should label the case above as **Case 1**, then provide a second case, where $a$ is odd and $b$ is even:

**Case 2:** 

\begin{align}
    a &= 2m + 1 \\
    b &= (2m + 1) + 1 \\
    &= 2m + 2
\end{align}

The product is

\begin{align}
    (2m + 1)\cdot (2m+2) &= 4m^2 + 4m + 2\\
    &= 2(2m^2+2m + 1)
\end{align}

which is clearly even.

We've shown that this conjecture is true if the smaller of the two consecutive numbers is even, and if the smaller of the two consecutive numbers is odd. These two cases cover all possible pairs of consecutive numbers, and in both cases, we found the statement to be true, so the conjecture is true. We are done!

Here's what the proof looks like in full:

```{proof}
We call our two consecutive numbers $a$ and $b$. W.l.o.g., let $a$ be the smaller of the two.

**Case 1:** $a$ even, $b$ odd.

\begin{align}
    a &= 2m \\
    b &= 2m + 1
\end{align}

Thus,

\begin{align}
  a \cdot b &= (2m)\cdot (2m+1) \\
  &= 4m^2 + 2m\\
  &= 2(2m^2+m)
\end{align}

which is clearly even.

**Case 2:** $a$ odd, $b$ even.

\begin{align}
    a &= 2m + 1 \\
    b &= (2m + 1) + 1 \\
    &= 2m + 2
\end{align}
    
Thus,

\begin{align}
    a \cdot b &= (2m + 1)\cdot (2m+2) \\
    &= 4m^2 + 4m + 2\\
    &= 2(2m^2+2m + 1) 
\end{align}

which is clearly even.

```

